### ISSUE TITLE
[Tracking] Offer MQTT API for pilot partners

### ISSUE THREAD

**Issue by haphut** [kahmalo/github-project-test-issue-repo#2]
## User story
As a pilot partner,
I can send test message to the MQTT API
so that I can innovate on an APC solution.

## Acceptance criteria
- [ ] MQTT topic structure has been defined
- [ ] MQTT broker is up and running
- [ ] MQTT broker has authentication and authorization figured out
- [ ] wildcard TLS certificate for APC has been procured
- [ ] DNS for dev.mqtt.apc.waltti.fi or similar has been defined
- [ ] necessary MQTT credentials have been delivered to partners securely
- [ ] partners have tested the API with a oneliner
